language: python
python:
    - "3.6"

notifications:
  email: false

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls
  - pip3 install coverage
  - python3 manage.py migrate

script:
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - coveralls