# Generated by Django 2.1.3 on 2018-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client')),
                ('position', models.CharField(max_length=100, verbose_name='Present position')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task title')),
                ('description', models.TextField(verbose_name='Task description')),
                ('controller_client', models.ManyToManyField(related_name='controller_in_tasks', to='city_tasks_api.Client', verbose_name='Controller')),
                ('performer_client', models.ManyToManyField(related_name='performer_in_tasks', to='city_tasks_api.Client', verbose_name='Performer')),
            ],
        ),
    ]
