# Generated by Django 2.1.3 on 2018-11-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_tasks_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_from_control', to='city_tasks_api.Client')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer_from_control', to='city_tasks_api.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='controller_client',
        ),
        migrations.RemoveField(
            model_name='task',
            name='performer_client',
        ),
        migrations.AddField(
            model_name='task',
            name='controller',
            field=models.ManyToManyField(related_name='controller_in_tasks', to='city_tasks_api.Client'),
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.ManyToManyField(related_name='performer_in_tasks', to='city_tasks_api.Client'),
        ),
        migrations.AddField(
            model_name='performcontrol',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfomed_task', to='city_tasks_api.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='performcontrol',
            unique_together={('task', 'performer', 'controller')},
        ),
    ]
